version: "3.8"

services:
  web:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      ./.env
  db:
    image: postgres:13
    restart: always
    env_file:
        - ./.env
