version: "3.8"

services:
    db:
        image: postgres:12
        restart: always
        volumes:
            - /home/db/postgres_data:/var/lib/postgresql/data:z
        ports:
            - "5432:5432"
        env_file:
            - ./.env
    web:
        build: .
        command: bash start.sh
        volumes:
            - .:/code
        expose:
            - "8000"
        ports:
            - 8000:8000
        depends_on:
            - db
        env_file:
            ./.env

volumes:
    postgres_data: