# Generated by Django 3.2 on 2021-05-02 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='sch',
            field=models.BooleanField(default=False),
        ),
    ]
